// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"

type AnimatedNumber interface{}

type AnimatedPoint interface{}

type AnimatedScale interface{}

type Asset interface{}

type Assets map[string]Asset

type Background interface{}

type CaptionEntry struct {
	// T corresponds to the JSON schema field "t".
	T float64 `json:"t" yaml:"t" mapstructure:"t"`

	// Text corresponds to the JSON schema field "text".
	Text string `json:"text" yaml:"text" mapstructure:"text"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CaptionEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["t"]; raw != nil && !ok {
		return fmt.Errorf("field t in CaptionEntry: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in CaptionEntry: required")
	}
	type Plain CaptionEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.T {
		return fmt.Errorf("field %s: must be >= %v", "t", 0)
	}
	*j = CaptionEntry(plain)
	return nil
}

type CaptionSequenceLayer struct {
	// Captions corresponds to the JSON schema field "captions".
	Captions []CaptionEntry `json:"captions" yaml:"captions" mapstructure:"captions"`

	// Color corresponds to the JSON schema field "color".
	Color *string `json:"color,omitempty,omitzero" yaml:"color,omitempty" mapstructure:"color,omitempty"`

	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Entrance corresponds to the JSON schema field "entrance".
	Entrance *TransitionConfig `json:"entrance,omitempty,omitzero" yaml:"entrance,omitempty" mapstructure:"entrance,omitempty"`

	// Exit corresponds to the JSON schema field "exit".
	Exit *TransitionConfig `json:"exit,omitempty,omitzero" yaml:"exit,omitempty" mapstructure:"exit,omitempty"`

	// Font corresponds to the JSON schema field "font".
	Font *Font `json:"font,omitempty,omitzero" yaml:"font,omitempty" mapstructure:"font,omitempty"`

	// MaxWidth corresponds to the JSON schema field "maxWidth".
	MaxWidth *float64 `json:"maxWidth,omitempty,omitzero" yaml:"maxWidth,omitempty" mapstructure:"maxWidth,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// Position corresponds to the JSON schema field "position".
	Position Point `json:"position,omitempty,omitzero" yaml:"position,omitempty" mapstructure:"position,omitempty"`

	// ShrinkToFit corresponds to the JSON schema field "shrinkToFit".
	ShrinkToFit *bool `json:"shrinkToFit,omitempty,omitzero" yaml:"shrinkToFit,omitempty" mapstructure:"shrinkToFit,omitempty"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CaptionSequenceLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["captions"]; raw != nil && !ok {
		return fmt.Errorf("field captions in CaptionSequenceLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CaptionSequenceLayer: required")
	}
	type Plain CaptionSequenceLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Captions != nil && len(plain.Captions) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "captions", 1)
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "captionSequence" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "captionSequence")
	}
	*j = CaptionSequenceLayer(plain)
	return nil
}

// Re-draws `source` through a different effect pipeline, clipped to the alpha of
// `mask`. `maskEffect` applies to the string form of `source` only; when `source`
// is a Layer, that layer's own `effects` are the pipeline.
type CompositeMaskLayer struct {
	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Mask corresponds to the JSON schema field "mask".
	Mask Layer `json:"mask" yaml:"mask" mapstructure:"mask"`

	// MaskEffect corresponds to the JSON schema field "maskEffect".
	MaskEffect Effect `json:"maskEffect,omitempty,omitzero" yaml:"maskEffect,omitempty" mapstructure:"maskEffect,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// Either an images-registry key (drawn full-canvas) or a Layer, which is drawn
	// through the normal layer pipeline and so honours `frame` and `downscaleBlur`.
	Source interface{} `json:"source" yaml:"source" mapstructure:"source"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompositeMaskLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mask"]; raw != nil && !ok {
		return fmt.Errorf("field mask in CompositeMaskLayer: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in CompositeMaskLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompositeMaskLayer: required")
	}
	type Plain CompositeMaskLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "compositeMask" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "compositeMask")
	}
	*j = CompositeMaskLayer(plain)
	return nil
}

// A predicate over `vars` deciding whether a layer is drawn at all — the one place
// document structure, rather than a value, may depend on a runtime fact. A layer
// that fails its condition is skipped entirely, and nothing moves to fill the gap:
// layout stays the author's job, so a document with an optional layer positions
// the layers around it for both cases. The string form names a var, with or
// without the `$var:` prefix, and holds when the value is truthy: `false`, `0`,
// `NaN`, the empty string, the strings `"false"` and `"0"`, and an unset var are
// all false, everything else true. The object form compares instead, as strings,
// so `1` and `"1"` match — an unset var never matches.
type Condition interface{}

type DataVizLayer struct {
	// Animation corresponds to the JSON schema field "animation".
	Animation DataVizLayerAnimation `json:"animation,omitempty,omitzero" yaml:"animation,omitempty" mapstructure:"animation,omitempty"`

	// Area corresponds to the JSON schema field "area".
	Area *DataVizLayerArea `json:"area,omitempty,omitzero" yaml:"area,omitempty" mapstructure:"area,omitempty"`

	// Data corresponds to the JSON schema field "data".
	Data DataVizLayerData `json:"data" yaml:"data" mapstructure:"data"`

	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Style corresponds to the JSON schema field "style".
	Style DataVizLayerStyle `json:"style,omitempty,omitzero" yaml:"style,omitempty" mapstructure:"style,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`

	// Viz corresponds to the JSON schema field "viz".
	Viz string `json:"viz" yaml:"viz" mapstructure:"viz"`
}

type DataVizLayerAnimation map[string]interface{}

type DataVizLayerArea struct {
	// Bottom corresponds to the JSON schema field "bottom".
	Bottom *float64 `json:"bottom,omitempty,omitzero" yaml:"bottom,omitempty" mapstructure:"bottom,omitempty"`

	// Left corresponds to the JSON schema field "left".
	Left *float64 `json:"left,omitempty,omitzero" yaml:"left,omitempty" mapstructure:"left,omitempty"`

	// Right corresponds to the JSON schema field "right".
	Right *float64 `json:"right,omitempty,omitzero" yaml:"right,omitempty" mapstructure:"right,omitempty"`

	// Top corresponds to the JSON schema field "top".
	Top *float64 `json:"top,omitempty,omitzero" yaml:"top,omitempty" mapstructure:"top,omitempty"`
}

type DataVizLayerData map[string]interface{}

type DataVizLayerStyle map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DataVizLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in DataVizLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in DataVizLayer: required")
	}
	if _, ok := raw["viz"]; raw != nil && !ok {
		return fmt.Errorf("field viz in DataVizLayer: required")
	}
	type Plain DataVizLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "dataViz" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "dataViz")
	}
	*j = DataVizLayer(plain)
	return nil
}

type DownscaleBlurEffect struct {
	// Radius corresponds to the JSON schema field "radius".
	Radius AnimatedNumber `json:"radius" yaml:"radius" mapstructure:"radius"`

	// Shrink corresponds to the JSON schema field "shrink".
	Shrink AnimatedNumber `json:"shrink" yaml:"shrink" mapstructure:"shrink"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DownscaleBlurEffect) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["radius"]; raw != nil && !ok {
		return fmt.Errorf("field radius in DownscaleBlurEffect: required")
	}
	if _, ok := raw["shrink"]; raw != nil && !ok {
		return fmt.Errorf("field shrink in DownscaleBlurEffect: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in DownscaleBlurEffect: required")
	}
	type Plain DownscaleBlurEffect
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Type != "downscaleBlur" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "downscaleBlur")
	}
	*j = DownscaleBlurEffect(plain)
	return nil
}

type DropShadowEffect struct {
	// Blur corresponds to the JSON schema field "blur".
	Blur AnimatedNumber `json:"blur" yaml:"blur" mapstructure:"blur"`

	// Color corresponds to the JSON schema field "color".
	Color string `json:"color" yaml:"color" mapstructure:"color"`

	// OffsetX corresponds to the JSON schema field "offsetX".
	OffsetX AnimatedNumber `json:"offsetX,omitempty,omitzero" yaml:"offsetX,omitempty" mapstructure:"offsetX,omitempty"`

	// OffsetY corresponds to the JSON schema field "offsetY".
	OffsetY AnimatedNumber `json:"offsetY,omitempty,omitzero" yaml:"offsetY,omitempty" mapstructure:"offsetY,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DropShadowEffect) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["blur"]; raw != nil && !ok {
		return fmt.Errorf("field blur in DropShadowEffect: required")
	}
	if _, ok := raw["color"]; raw != nil && !ok {
		return fmt.Errorf("field color in DropShadowEffect: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in DropShadowEffect: required")
	}
	type Plain DropShadowEffect
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Type != "dropShadow" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "dropShadow")
	}
	*j = DropShadowEffect(plain)
	return nil
}

type EasingName interface{}

type Effect interface{}

type Font struct {
	// Asset corresponds to the JSON schema field "asset".
	Asset *string `json:"asset,omitempty,omitzero" yaml:"asset,omitempty" mapstructure:"asset,omitempty"`

	// Size corresponds to the JSON schema field "size".
	Size float64 `json:"size" yaml:"size" mapstructure:"size"`

	// Weight corresponds to the JSON schema field "weight".
	Weight *float64 `json:"weight,omitempty,omitzero" yaml:"weight,omitempty" mapstructure:"weight,omitempty"`
}

// A typeface the document expects to be available. Declaring it does not load it:
// the renderer never fetches a face, so the host must have the family loaded
// before the first frame is drawn. An unloaded family falls through `fallback` to
// a generic and renders in the wrong typeface with no error, so preload every font
// asset a document declares — `requiredFonts(doc)` in @variax-ai/video-renderer
// lists them.
type FontAsset struct {
	// Additional families tried after `family`, in order, forming the CSS font stack.
	Fallback []string `json:"fallback,omitempty,omitzero" yaml:"fallback,omitempty" mapstructure:"fallback,omitempty"`

	// The CSS family name the loaded face is registered under. Must match the host's
	// registration exactly, including case.
	Family string `json:"family" yaml:"family" mapstructure:"family"`

	// Where the face can be obtained. Advisory only — the renderer never reads it. It
	// is recorded so a host (or a build step) knows what to load for `family`.
	Src string `json:"src" yaml:"src" mapstructure:"src"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// Default weight for text bound to this asset, used when the text layer's font
	// declares none. Defaults to 400.
	Weight *float64 `json:"weight,omitempty,omitzero" yaml:"weight,omitempty" mapstructure:"weight,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FontAsset) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["family"]; raw != nil && !ok {
		return fmt.Errorf("field family in FontAsset: required")
	}
	if _, ok := raw["src"]; raw != nil && !ok {
		return fmt.Errorf("field src in FontAsset: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in FontAsset: required")
	}
	type Plain FontAsset
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Type != "font" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "font")
	}
	*j = FontAsset(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Font) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["size"]; raw != nil && !ok {
		return fmt.Errorf("field size in Font: required")
	}
	type Plain Font
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 >= plain.Size {
		return fmt.Errorf("field %s: must be > %v", "size", 0)
	}
	*j = Font(plain)
	return nil
}

type Frame struct {
	// H corresponds to the JSON schema field "h".
	H float64 `json:"h" yaml:"h" mapstructure:"h"`

	// Radius corresponds to the JSON schema field "radius".
	Radius *float64 `json:"radius,omitempty,omitzero" yaml:"radius,omitempty" mapstructure:"radius,omitempty"`

	// W corresponds to the JSON schema field "w".
	W float64 `json:"w" yaml:"w" mapstructure:"w"`

	// X corresponds to the JSON schema field "x".
	X float64 `json:"x" yaml:"x" mapstructure:"x"`

	// Y corresponds to the JSON schema field "y".
	Y float64 `json:"y" yaml:"y" mapstructure:"y"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Frame) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["h"]; raw != nil && !ok {
		return fmt.Errorf("field h in Frame: required")
	}
	if _, ok := raw["w"]; raw != nil && !ok {
		return fmt.Errorf("field w in Frame: required")
	}
	if _, ok := raw["x"]; raw != nil && !ok {
		return fmt.Errorf("field x in Frame: required")
	}
	if _, ok := raw["y"]; raw != nil && !ok {
		return fmt.Errorf("field y in Frame: required")
	}
	type Plain Frame
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Frame(plain)
	return nil
}

type GaussianBlurEffect struct {
	// Radius corresponds to the JSON schema field "radius".
	Radius AnimatedNumber `json:"radius" yaml:"radius" mapstructure:"radius"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GaussianBlurEffect) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["radius"]; raw != nil && !ok {
		return fmt.Errorf("field radius in GaussianBlurEffect: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GaussianBlurEffect: required")
	}
	type Plain GaussianBlurEffect
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Type != "gaussianBlur" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "gaussianBlur")
	}
	*j = GaussianBlurEffect(plain)
	return nil
}

type Generator struct {
	// Generator corresponds to the JSON schema field "generator".
	Generator GeneratorGenerator `json:"generator" yaml:"generator" mapstructure:"generator"`
}

type GeneratorGenerator struct {
	// Fn corresponds to the JSON schema field "fn".
	Fn GeneratorGeneratorFn `json:"fn" yaml:"fn" mapstructure:"fn"`

	// Id corresponds to the JSON schema field "id".
	Id *string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// Generator parameters. Every generator additionally accepts `startMs`, which
	// shifts its time origin: the generator is evaluated at `tMs - startMs`. Defaults
	// to 0 (absolute clip time).
	Params GeneratorGeneratorParams `json:"params,omitempty,omitzero" yaml:"params,omitempty" mapstructure:"params,omitempty"`
}

type GeneratorGeneratorFn string

const GeneratorGeneratorFnCountUp GeneratorGeneratorFn = "countUp"
const GeneratorGeneratorFnPulse GeneratorGeneratorFn = "pulse"
const GeneratorGeneratorFnSine GeneratorGeneratorFn = "sine"
const GeneratorGeneratorFnSineOscillation GeneratorGeneratorFn = "sineOscillation"
const GeneratorGeneratorFnSineStrokes GeneratorGeneratorFn = "sineStrokes"

var enumValues_GeneratorGeneratorFn = []interface{}{
	"sine",
	"sineStrokes",
	"sineOscillation",
	"pulse",
	"countUp",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GeneratorGeneratorFn) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_GeneratorGeneratorFn {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_GeneratorGeneratorFn, v)
	}
	*j = GeneratorGeneratorFn(v)
	return nil
}

// Generator parameters. Every generator additionally accepts `startMs`, which
// shifts its time origin: the generator is evaluated at `tMs - startMs`. Defaults
// to 0 (absolute clip time).
type GeneratorGeneratorParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GeneratorGenerator) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["fn"]; raw != nil && !ok {
		return fmt.Errorf("field fn in GeneratorGenerator: required")
	}
	type Plain GeneratorGenerator
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GeneratorGenerator(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Generator) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["generator"]; raw != nil && !ok {
		return fmt.Errorf("field generator in Generator: required")
	}
	type Plain Generator
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Generator(plain)
	return nil
}

type GroupLayer struct {
	// Children corresponds to the JSON schema field "children".
	Children []Layer `json:"children" yaml:"children" mapstructure:"children"`

	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// Position corresponds to the JSON schema field "position".
	Position Point `json:"position,omitempty,omitzero" yaml:"position,omitempty" mapstructure:"position,omitempty"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GroupLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["children"]; raw != nil && !ok {
		return fmt.Errorf("field children in GroupLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GroupLayer: required")
	}
	type Plain GroupLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "group" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "group")
	}
	*j = GroupLayer(plain)
	return nil
}

type ImageAsset struct {
	// Src corresponds to the JSON schema field "src".
	Src string `json:"src" yaml:"src" mapstructure:"src"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ImageAsset) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["src"]; raw != nil && !ok {
		return fmt.Errorf("field src in ImageAsset: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ImageAsset: required")
	}
	type Plain ImageAsset
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Type != "image" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "image")
	}
	*j = ImageAsset(plain)
	return nil
}

type ImageLayer struct {
	// Asset corresponds to the JSON schema field "asset".
	Asset string `json:"asset" yaml:"asset" mapstructure:"asset"`

	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Frame corresponds to the JSON schema field "frame".
	Frame *Frame `json:"frame,omitempty,omitzero" yaml:"frame,omitempty" mapstructure:"frame,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ImageLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset"]; raw != nil && !ok {
		return fmt.Errorf("field asset in ImageLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ImageLayer: required")
	}
	type Plain ImageLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "image" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "image")
	}
	*j = ImageLayer(plain)
	return nil
}

type Layer interface{}

type NumberKeyframe struct {
	// Easing corresponds to the JSON schema field "easing".
	Easing EasingName `json:"easing,omitempty,omitzero" yaml:"easing,omitempty" mapstructure:"easing,omitempty"`

	// T corresponds to the JSON schema field "t".
	T float64 `json:"t" yaml:"t" mapstructure:"t"`

	// Value corresponds to the JSON schema field "value".
	Value float64 `json:"value" yaml:"value" mapstructure:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NumberKeyframe) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["t"]; raw != nil && !ok {
		return fmt.Errorf("field t in NumberKeyframe: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in NumberKeyframe: required")
	}
	type Plain NumberKeyframe
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.T {
		return fmt.Errorf("field %s: must be >= %v", "t", 0)
	}
	*j = NumberKeyframe(plain)
	return nil
}

type Point []float64

type PointKeyframe struct {
	// Easing corresponds to the JSON schema field "easing".
	Easing EasingName `json:"easing,omitempty,omitzero" yaml:"easing,omitempty" mapstructure:"easing,omitempty"`

	// T corresponds to the JSON schema field "t".
	T float64 `json:"t" yaml:"t" mapstructure:"t"`

	// Value corresponds to the JSON schema field "value".
	Value Point `json:"value" yaml:"value" mapstructure:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PointKeyframe) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["t"]; raw != nil && !ok {
		return fmt.Errorf("field t in PointKeyframe: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in PointKeyframe: required")
	}
	type Plain PointKeyframe
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.T {
		return fmt.Errorf("field %s: must be >= %v", "t", 0)
	}
	*j = PointKeyframe(plain)
	return nil
}

type RefLayer struct {
	// Color corresponds to the JSON schema field "color".
	Color *string `json:"color,omitempty,omitzero" yaml:"color,omitempty" mapstructure:"color,omitempty"`

	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Params corresponds to the JSON schema field "params".
	Params RefLayerParams `json:"params,omitempty,omitzero" yaml:"params,omitempty" mapstructure:"params,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// Position corresponds to the JSON schema field "position".
	Position Point `json:"position,omitempty,omitzero" yaml:"position,omitempty" mapstructure:"position,omitempty"`

	// Size corresponds to the JSON schema field "size".
	Size *float64 `json:"size,omitempty,omitzero" yaml:"size,omitempty" mapstructure:"size,omitempty"`

	// Src corresponds to the JSON schema field "src".
	Src string `json:"src" yaml:"src" mapstructure:"src"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`
}

type RefLayerParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RefLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["src"]; raw != nil && !ok {
		return fmt.Errorf("field src in RefLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in RefLayer: required")
	}
	type Plain RefLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if matched, _ := regexp.MatchString(`^#`, string(plain.Src)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Src", `^#`)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "ref" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "ref")
	}
	*j = RefLayer(plain)
	return nil
}

type RepeaterLayer struct {
	// Child corresponds to the JSON schema field "child".
	Child Layer `json:"child" yaml:"child" mapstructure:"child"`

	// Count corresponds to the JSON schema field "count".
	Count int `json:"count" yaml:"count" mapstructure:"count"`

	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// PhaseOffsetMs corresponds to the JSON schema field "phaseOffsetMs".
	PhaseOffsetMs *float64 `json:"phaseOffsetMs,omitempty,omitzero" yaml:"phaseOffsetMs,omitempty" mapstructure:"phaseOffsetMs,omitempty"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RepeaterLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["child"]; raw != nil && !ok {
		return fmt.Errorf("field child in RepeaterLayer: required")
	}
	if _, ok := raw["count"]; raw != nil && !ok {
		return fmt.Errorf("field count in RepeaterLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in RepeaterLayer: required")
	}
	type Plain RepeaterLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Count {
		return fmt.Errorf("field %s: must be >= %v", "count", 1)
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "repeater" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "repeater")
	}
	*j = RepeaterLayer(plain)
	return nil
}

// A single JSON value a var can hold. Spelled as an `anyOf` of one-type schemas
// rather than a `type` array, so a validator running in strict mode compiles it
// without configuration.
type Scalar interface{}

type Scene struct {
	// Background corresponds to the JSON schema field "background".
	Background Background `json:"background,omitempty,omitzero" yaml:"background,omitempty" mapstructure:"background,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs float64 `json:"endMs" yaml:"endMs" mapstructure:"endMs"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Layers corresponds to the JSON schema field "layers".
	Layers []Layer `json:"layers" yaml:"layers" mapstructure:"layers"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs float64 `json:"startMs" yaml:"startMs" mapstructure:"startMs"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Scene) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["endMs"]; raw != nil && !ok {
		return fmt.Errorf("field endMs in Scene: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Scene: required")
	}
	if _, ok := raw["layers"]; raw != nil && !ok {
		return fmt.Errorf("field layers in Scene: required")
	}
	if _, ok := raw["startMs"]; raw != nil && !ok {
		return fmt.Errorf("field startMs in Scene: required")
	}
	type Plain Scene
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if 0 > plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	*j = Scene(plain)
	return nil
}

type Shadow struct {
	// Blur corresponds to the JSON schema field "blur".
	Blur float64 `json:"blur" yaml:"blur" mapstructure:"blur"`

	// Color corresponds to the JSON schema field "color".
	Color string `json:"color" yaml:"color" mapstructure:"color"`

	// OffsetX corresponds to the JSON schema field "offsetX".
	OffsetX *float64 `json:"offsetX,omitempty,omitzero" yaml:"offsetX,omitempty" mapstructure:"offsetX,omitempty"`

	// OffsetY corresponds to the JSON schema field "offsetY".
	OffsetY *float64 `json:"offsetY,omitempty,omitzero" yaml:"offsetY,omitempty" mapstructure:"offsetY,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Shadow) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["blur"]; raw != nil && !ok {
		return fmt.Errorf("field blur in Shadow: required")
	}
	if _, ok := raw["color"]; raw != nil && !ok {
		return fmt.Errorf("field color in Shadow: required")
	}
	type Plain Shadow
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Shadow(plain)
	return nil
}

type ShapeLayer struct {
	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Fill corresponds to the JSON schema field "fill".
	Fill *string `json:"fill,omitempty,omitzero" yaml:"fill,omitempty" mapstructure:"fill,omitempty"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty,omitzero" yaml:"path,omitempty" mapstructure:"path,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// Position corresponds to the JSON schema field "position".
	Position Point `json:"position,omitempty,omitzero" yaml:"position,omitempty" mapstructure:"position,omitempty"`

	// Radius corresponds to the JSON schema field "radius".
	Radius *float64 `json:"radius,omitempty,omitzero" yaml:"radius,omitempty" mapstructure:"radius,omitempty"`

	// Shadow corresponds to the JSON schema field "shadow".
	Shadow *Shadow `json:"shadow,omitempty,omitzero" yaml:"shadow,omitempty" mapstructure:"shadow,omitempty"`

	// Shape corresponds to the JSON schema field "shape".
	Shape ShapeLayerShape `json:"shape" yaml:"shape" mapstructure:"shape"`

	// Size corresponds to the JSON schema field "size".
	Size []float64 `json:"size,omitempty,omitzero" yaml:"size,omitempty" mapstructure:"size,omitempty"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Stroke corresponds to the JSON schema field "stroke".
	Stroke *Stroke `json:"stroke,omitempty,omitzero" yaml:"stroke,omitempty" mapstructure:"stroke,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`
}

type ShapeLayerShape string

const ShapeLayerShapeEllipse ShapeLayerShape = "ellipse"
const ShapeLayerShapeLine ShapeLayerShape = "line"
const ShapeLayerShapePath ShapeLayerShape = "path"
const ShapeLayerShapeRect ShapeLayerShape = "rect"
const ShapeLayerShapeRoundedRect ShapeLayerShape = "roundedRect"

var enumValues_ShapeLayerShape = []interface{}{
	"rect",
	"roundedRect",
	"ellipse",
	"path",
	"line",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ShapeLayerShape) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ShapeLayerShape {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ShapeLayerShape, v)
	}
	*j = ShapeLayerShape(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ShapeLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["shape"]; raw != nil && !ok {
		return fmt.Errorf("field shape in ShapeLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ShapeLayer: required")
	}
	type Plain ShapeLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.Size != nil && len(plain.Size) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "size", 2)
	}
	if len(plain.Size) > 2 {
		return fmt.Errorf("field %s length: must be <= %d", "size", 2)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "shape" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "shape")
	}
	*j = ShapeLayer(plain)
	return nil
}

type StatBeatEntry struct {
	// CountUpMs corresponds to the JSON schema field "countUpMs".
	CountUpMs *float64 `json:"countUpMs,omitempty,omitzero" yaml:"countUpMs,omitempty" mapstructure:"countUpMs,omitempty"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label" yaml:"label" mapstructure:"label"`

	// OffsetMs corresponds to the JSON schema field "offsetMs".
	OffsetMs *float64 `json:"offsetMs,omitempty,omitzero" yaml:"offsetMs,omitempty" mapstructure:"offsetMs,omitempty"`

	// Position corresponds to the JSON schema field "position".
	Position Point `json:"position" yaml:"position" mapstructure:"position"`

	// Value corresponds to the JSON schema field "value".
	Value interface{} `json:"value" yaml:"value" mapstructure:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StatBeatEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in StatBeatEntry: required")
	}
	if _, ok := raw["position"]; raw != nil && !ok {
		return fmt.Errorf("field position in StatBeatEntry: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in StatBeatEntry: required")
	}
	type Plain StatBeatEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = StatBeatEntry(plain)
	return nil
}

type StatBeatLayer struct {
	// Beats corresponds to the JSON schema field "beats".
	Beats []StatBeatEntry `json:"beats" yaml:"beats" mapstructure:"beats"`

	// Easing corresponds to the JSON schema field "easing".
	Easing EasingName `json:"easing,omitempty,omitzero" yaml:"easing,omitempty" mapstructure:"easing,omitempty"`

	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Entrance corresponds to the JSON schema field "entrance".
	Entrance *string `json:"entrance,omitempty,omitzero" yaml:"entrance,omitempty" mapstructure:"entrance,omitempty"`

	// LabelColor corresponds to the JSON schema field "labelColor".
	LabelColor *string `json:"labelColor,omitempty,omitzero" yaml:"labelColor,omitempty" mapstructure:"labelColor,omitempty"`

	// LabelFont corresponds to the JSON schema field "labelFont".
	LabelFont *Font `json:"labelFont,omitempty,omitzero" yaml:"labelFont,omitempty" mapstructure:"labelFont,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// ValueColor corresponds to the JSON schema field "valueColor".
	ValueColor *string `json:"valueColor,omitempty,omitzero" yaml:"valueColor,omitempty" mapstructure:"valueColor,omitempty"`

	// ValueFont corresponds to the JSON schema field "valueFont".
	ValueFont *Font `json:"valueFont,omitempty,omitzero" yaml:"valueFont,omitempty" mapstructure:"valueFont,omitempty"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StatBeatLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["beats"]; raw != nil && !ok {
		return fmt.Errorf("field beats in StatBeatLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in StatBeatLayer: required")
	}
	type Plain StatBeatLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Beats != nil && len(plain.Beats) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "beats", 1)
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "statBeat" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "statBeat")
	}
	*j = StatBeatLayer(plain)
	return nil
}

type Stroke struct {
	// Color corresponds to the JSON schema field "color".
	Color string `json:"color" yaml:"color" mapstructure:"color"`

	// Width corresponds to the JSON schema field "width".
	Width float64 `json:"width" yaml:"width" mapstructure:"width"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Stroke) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["color"]; raw != nil && !ok {
		return fmt.Errorf("field color in Stroke: required")
	}
	if _, ok := raw["width"]; raw != nil && !ok {
		return fmt.Errorf("field width in Stroke: required")
	}
	type Plain Stroke
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Stroke(plain)
	return nil
}

type TemplateString struct {
	// Bindings corresponds to the JSON schema field "bindings".
	Bindings TemplateStringBindings `json:"bindings,omitempty,omitzero" yaml:"bindings,omitempty" mapstructure:"bindings,omitempty"`

	// Template corresponds to the JSON schema field "template".
	Template string `json:"template" yaml:"template" mapstructure:"template"`
}

type TemplateStringBindings map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TemplateString) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["template"]; raw != nil && !ok {
		return fmt.Errorf("field template in TemplateString: required")
	}
	type Plain TemplateString
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TemplateString(plain)
	return nil
}

type TextLayer struct {
	// Align corresponds to the JSON schema field "align".
	Align *TextLayerAlign `json:"align,omitempty,omitzero" yaml:"align,omitempty" mapstructure:"align,omitempty"`

	// Color corresponds to the JSON schema field "color".
	Color *string `json:"color,omitempty,omitzero" yaml:"color,omitempty" mapstructure:"color,omitempty"`

	// Content corresponds to the JSON schema field "content".
	Content interface{} `json:"content" yaml:"content" mapstructure:"content"`

	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Font corresponds to the JSON schema field "font".
	Font *Font `json:"font,omitempty,omitzero" yaml:"font,omitempty" mapstructure:"font,omitempty"`

	// LineHeight corresponds to the JSON schema field "lineHeight".
	LineHeight *float64 `json:"lineHeight,omitempty,omitzero" yaml:"lineHeight,omitempty" mapstructure:"lineHeight,omitempty"`

	// MaxWidth corresponds to the JSON schema field "maxWidth".
	MaxWidth *float64 `json:"maxWidth,omitempty,omitzero" yaml:"maxWidth,omitempty" mapstructure:"maxWidth,omitempty"`

	// MinSize corresponds to the JSON schema field "minSize".
	MinSize *float64 `json:"minSize,omitempty,omitzero" yaml:"minSize,omitempty" mapstructure:"minSize,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// Position corresponds to the JSON schema field "position".
	Position Point `json:"position,omitempty,omitzero" yaml:"position,omitempty" mapstructure:"position,omitempty"`

	// ShrinkToFit corresponds to the JSON schema field "shrinkToFit".
	ShrinkToFit *bool `json:"shrinkToFit,omitempty,omitzero" yaml:"shrinkToFit,omitempty" mapstructure:"shrinkToFit,omitempty"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`

	// Wrap corresponds to the JSON schema field "wrap".
	Wrap *bool `json:"wrap,omitempty,omitzero" yaml:"wrap,omitempty" mapstructure:"wrap,omitempty"`
}

type TextLayerAlign string

const TextLayerAlignCenter TextLayerAlign = "center"
const TextLayerAlignLeft TextLayerAlign = "left"
const TextLayerAlignRight TextLayerAlign = "right"

var enumValues_TextLayerAlign = []interface{}{
	"left",
	"center",
	"right",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TextLayerAlign) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TextLayerAlign {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TextLayerAlign, v)
	}
	*j = TextLayerAlign(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TextLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["content"]; raw != nil && !ok {
		return fmt.Errorf("field content in TextLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in TextLayer: required")
	}
	type Plain TextLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Type != "text" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "text")
	}
	*j = TextLayer(plain)
	return nil
}

type Tokens map[string]string

// Motion history: samples `source` at past times and unions a circle per sample,
// radius shrinking with age. Emits vector geometry only (no imagery), which is
// what makes it usable as a compositeMask mask. `source` is the moving point whose
// path is sampled — it must be declarative so the renderer can re-evaluate it at
// past times, and is interpreted in absolute document coordinates. `radius` is the
// radius of the freshest sample. `stroke` draws a polyline through the sample
// centres with round caps and joins. Samples older than the layer's own `startMs`
// are dropped.
type TrailLayer struct {
	// Effects corresponds to the JSON schema field "effects".
	Effects []Effect `json:"effects,omitempty,omitzero" yaml:"effects,omitempty" mapstructure:"effects,omitempty"`

	// EndMs corresponds to the JSON schema field "endMs".
	EndMs *float64 `json:"endMs,omitempty,omitzero" yaml:"endMs,omitempty" mapstructure:"endMs,omitempty"`

	// Fraction of the radius shed across the full window: sample i has radius `radius
	// * (1 - falloff * i / samples)`. Defaults to 0.
	Falloff *float64 `json:"falloff,omitempty,omitzero" yaml:"falloff,omitempty" mapstructure:"falloff,omitempty"`

	// Fills the union of circles. Defaults to #ffffff when no `stroke` is given.
	Fill *string `json:"fill,omitempty,omitzero" yaml:"fill,omitempty" mapstructure:"fill,omitempty"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty,omitzero" yaml:"persist,omitempty" mapstructure:"persist,omitempty"`

	// Radius corresponds to the JSON schema field "radius".
	Radius AnimatedNumber `json:"radius" yaml:"radius" mapstructure:"radius"`

	// Number of samples in the age schedule.
	Samples int `json:"samples" yaml:"samples" mapstructure:"samples"`

	// Source corresponds to the JSON schema field "source".
	Source AnimatedPoint `json:"source" yaml:"source" mapstructure:"source"`

	// StartMs corresponds to the JSON schema field "startMs".
	StartMs *float64 `json:"startMs,omitempty,omitzero" yaml:"startMs,omitempty" mapstructure:"startMs,omitempty"`

	// Stroke corresponds to the JSON schema field "stroke".
	Stroke *Stroke `json:"stroke,omitempty,omitzero" yaml:"stroke,omitempty" mapstructure:"stroke,omitempty"`

	// Draw only the N freshest samples, keeping the age schedule computed over
	// `samples`. Defaults to `samples`.
	Take *int `json:"take,omitempty,omitzero" yaml:"take,omitempty" mapstructure:"take,omitempty"`

	// Transform corresponds to the JSON schema field "transform".
	Transform *Transform `json:"transform,omitempty,omitzero" yaml:"transform,omitempty" mapstructure:"transform,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// VisibleIf corresponds to the JSON schema field "visibleIf".
	VisibleIf Condition `json:"visibleIf,omitempty,omitzero" yaml:"visibleIf,omitempty" mapstructure:"visibleIf,omitempty"`

	// How far back the trail reaches. Sample i sits at `tMs - i * windowMs /
	// samples`.
	WindowMs float64 `json:"windowMs" yaml:"windowMs" mapstructure:"windowMs"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TrailLayer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["radius"]; raw != nil && !ok {
		return fmt.Errorf("field radius in TrailLayer: required")
	}
	if _, ok := raw["samples"]; raw != nil && !ok {
		return fmt.Errorf("field samples in TrailLayer: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in TrailLayer: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in TrailLayer: required")
	}
	if _, ok := raw["windowMs"]; raw != nil && !ok {
		return fmt.Errorf("field windowMs in TrailLayer: required")
	}
	type Plain TrailLayer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.EndMs != nil && 0 > *plain.EndMs {
		return fmt.Errorf("field %s: must be >= %v", "endMs", 0)
	}
	if plain.Falloff != nil && 1 < *plain.Falloff {
		return fmt.Errorf("field %s: must be <= %v", "falloff", 1)
	}
	if plain.Falloff != nil && 0 > *plain.Falloff {
		return fmt.Errorf("field %s: must be >= %v", "falloff", 0)
	}
	if 1 > plain.Samples {
		return fmt.Errorf("field %s: must be >= %v", "samples", 1)
	}
	if plain.StartMs != nil && 0 > *plain.StartMs {
		return fmt.Errorf("field %s: must be >= %v", "startMs", 0)
	}
	if plain.Take != nil && 1 > *plain.Take {
		return fmt.Errorf("field %s: must be >= %v", "take", 1)
	}
	if plain.Type != "trail" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "trail")
	}
	if 0 >= plain.WindowMs {
		return fmt.Errorf("field %s: must be > %v", "windowMs", 0)
	}
	*j = TrailLayer(plain)
	return nil
}

type Transform struct {
	// Anchor corresponds to the JSON schema field "anchor".
	Anchor Point `json:"anchor,omitempty,omitzero" yaml:"anchor,omitempty" mapstructure:"anchor,omitempty"`

	// Opacity corresponds to the JSON schema field "opacity".
	Opacity AnimatedNumber `json:"opacity,omitempty,omitzero" yaml:"opacity,omitempty" mapstructure:"opacity,omitempty"`

	// Position corresponds to the JSON schema field "position".
	Position AnimatedPoint `json:"position,omitempty,omitzero" yaml:"position,omitempty" mapstructure:"position,omitempty"`

	// Rotation corresponds to the JSON schema field "rotation".
	Rotation AnimatedNumber `json:"rotation,omitempty,omitzero" yaml:"rotation,omitempty" mapstructure:"rotation,omitempty"`

	// Scale corresponds to the JSON schema field "scale".
	Scale AnimatedScale `json:"scale,omitempty,omitzero" yaml:"scale,omitempty" mapstructure:"scale,omitempty"`
}

type TransitionConfig struct {
	// DurationMs corresponds to the JSON schema field "durationMs".
	DurationMs *float64 `json:"durationMs,omitempty,omitzero" yaml:"durationMs,omitempty" mapstructure:"durationMs,omitempty"`

	// RisePx corresponds to the JSON schema field "risePx".
	RisePx *float64 `json:"risePx,omitempty,omitzero" yaml:"risePx,omitempty" mapstructure:"risePx,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TransitionConfig) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in TransitionConfig: required")
	}
	type Plain TransitionConfig
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TransitionConfig(plain)
	return nil
}

// A declarative JSON format for motion-graphics videos, inspired by the Lottie
// schema.
type V1Json struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema *string `json:"$schema,omitempty,omitzero" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// Assets corresponds to the JSON schema field "assets".
	Assets Assets `json:"assets,omitempty,omitzero" yaml:"assets,omitempty" mapstructure:"assets,omitempty"`

	// DurationMs corresponds to the JSON schema field "durationMs".
	DurationMs float64 `json:"durationMs" yaml:"durationMs" mapstructure:"durationMs"`

	// Fps corresponds to the JSON schema field "fps".
	Fps float64 `json:"fps" yaml:"fps" mapstructure:"fps"`

	// Height corresponds to the JSON schema field "height".
	Height int `json:"height" yaml:"height" mapstructure:"height"`

	// Scenes corresponds to the JSON schema field "scenes".
	Scenes []Scene `json:"scenes" yaml:"scenes" mapstructure:"scenes"`

	// Tokens corresponds to the JSON schema field "tokens".
	Tokens Tokens `json:"tokens,omitempty,omitzero" yaml:"tokens,omitempty" mapstructure:"tokens,omitempty"`

	// Vars corresponds to the JSON schema field "vars".
	Vars Vars `json:"vars,omitempty,omitzero" yaml:"vars,omitempty" mapstructure:"vars,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version" yaml:"version" mapstructure:"version"`

	// Width corresponds to the JSON schema field "width".
	Width int `json:"width" yaml:"width" mapstructure:"width"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *V1Json) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["durationMs"]; raw != nil && !ok {
		return fmt.Errorf("field durationMs in V1Json: required")
	}
	if _, ok := raw["fps"]; raw != nil && !ok {
		return fmt.Errorf("field fps in V1Json: required")
	}
	if _, ok := raw["height"]; raw != nil && !ok {
		return fmt.Errorf("field height in V1Json: required")
	}
	if _, ok := raw["scenes"]; raw != nil && !ok {
		return fmt.Errorf("field scenes in V1Json: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in V1Json: required")
	}
	if _, ok := raw["width"]; raw != nil && !ok {
		return fmt.Errorf("field width in V1Json: required")
	}
	type Plain V1Json
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 >= plain.DurationMs {
		return fmt.Errorf("field %s: must be > %v", "durationMs", 0)
	}
	if 0 >= plain.Fps {
		return fmt.Errorf("field %s: must be > %v", "fps", 0)
	}
	if 0 >= plain.Height {
		return fmt.Errorf("field %s: must be > %v", "height", 0)
	}
	if plain.Scenes != nil && len(plain.Scenes) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "scenes", 1)
	}
	if plain.Version != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "version", 1)
	}
	if 0 >= plain.Width {
		return fmt.Errorf("field %s: must be > %v", "width", 0)
	}
	*j = V1Json(plain)
	return nil
}

type VarDefinition struct {
	// Default corresponds to the JSON schema field "default".
	Default interface{} `json:"default,omitempty,omitzero" yaml:"default,omitempty" mapstructure:"default,omitempty"`

	// Required corresponds to the JSON schema field "required".
	Required *bool `json:"required,omitempty,omitzero" yaml:"required,omitempty" mapstructure:"required,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type VarDefinitionType `json:"type" yaml:"type" mapstructure:"type"`
}

type VarDefinitionType string

const VarDefinitionTypeBoolean VarDefinitionType = "boolean"
const VarDefinitionTypeNumber VarDefinitionType = "number"
const VarDefinitionTypeString VarDefinitionType = "string"

var enumValues_VarDefinitionType = []interface{}{
	"string",
	"number",
	"boolean",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VarDefinitionType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_VarDefinitionType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_VarDefinitionType, v)
	}
	*j = VarDefinitionType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VarDefinition) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in VarDefinition: required")
	}
	type Plain VarDefinition
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = VarDefinition(plain)
	return nil
}

type Vars map[string]VarDefinition
