/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Asset = ImageAsset | FontAsset;
export type Background =
  | string
  | {
      type: "linearGradient" | "radialGradient";
      /**
       * @minItems 2
       */
      stops: [string, string, ...string[]];
      angle?: number;
    };
export type Layer =
  | ShapeLayer
  | TextLayer
  | ImageLayer
  | GroupLayer
  | RefLayer
  | RepeaterLayer
  | CaptionSequenceLayer
  | CompositeMaskLayer
  | DataVizLayer
  | StatBeatLayer;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Point = [number, number];
export type AnimatedPoint =
  | Point
  | {
      /**
       * @minItems 1
       */
      keyframes: [PointKeyframe, ...PointKeyframe[]];
    }
  | Generator;
export type EasingName =
  | ("linear" | "easeOutCubic" | "easeInOut" | "easeOutBack" | "easeInCubic")
  | {
      /**
       * @minItems 4
       * @maxItems 4
       */
      bezier: [number, number, number, number];
    };
export type AnimatedScale =
  | number
  | Point
  | {
      /**
       * @minItems 1
       */
      keyframes: [NumberKeyframe, ...NumberKeyframe[]];
    }
  | {
      /**
       * @minItems 1
       */
      keyframes: [PointKeyframe, ...PointKeyframe[]];
    }
  | Generator;
export type AnimatedNumber =
  | number
  | {
      /**
       * @minItems 1
       */
      keyframes: [NumberKeyframe, ...NumberKeyframe[]];
    }
  | Generator;
export type Effect = GaussianBlurEffect | DropShadowEffect | DownscaleBlurEffect;

/**
 * A declarative JSON format for motion-graphics videos, inspired by the Lottie schema.
 */
export interface VideoDocument {
  $schema?: string;
  version: 1;
  width: number;
  height: number;
  fps: number;
  durationMs: number;
  vars?: Vars;
  assets?: Assets;
  tokens?: Tokens;
  /**
   * @minItems 1
   */
  scenes: [Scene, ...Scene[]];
  [k: string]: unknown;
}
export interface Vars {
  [k: string]: VarDefinition;
}
export interface VarDefinition {
  type: "string" | "number" | "boolean";
  required?: boolean;
  default?: unknown;
}
export interface Assets {
  [k: string]: Asset;
}
export interface ImageAsset {
  type: "image";
  src: string;
}
export interface FontAsset {
  type: "font";
  family: string;
  weight?: number;
  src: string;
}
export interface Tokens {
  [k: string]: string;
}
export interface Scene {
  id: string;
  startMs: number;
  endMs: number;
  background?: Background;
  layers: Layer[];
}
export interface ShapeLayer {
  type: "shape";
  shape: "rect" | "roundedRect" | "ellipse" | "path" | "line";
  /**
   * @minItems 2
   * @maxItems 2
   */
  size?: [number, number];
  radius?: number;
  fill?: string;
  stroke?: Stroke;
  shadow?: Shadow;
  path?: string;
  position?: Point;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface Stroke {
  color: string;
  width: number;
}
export interface Shadow {
  color: string;
  blur: number;
  offsetX?: number;
  offsetY?: number;
}
export interface Transform {
  position?: AnimatedPoint;
  scale?: AnimatedScale;
  rotation?: AnimatedNumber;
  opacity?: AnimatedNumber;
  anchor?: Point;
}
export interface PointKeyframe {
  t: number;
  value: Point;
  easing?: EasingName;
}
export interface Generator {
  generator: {
    fn: "sine" | "sineStrokes" | "sineOscillation" | "pulse" | "countUp";
    params?: {
      [k: string]: unknown;
    };
    id?: string;
  };
}
export interface NumberKeyframe {
  t: number;
  value: number;
  easing?: EasingName;
}
export interface GaussianBlurEffect {
  type: "gaussianBlur";
  radius: AnimatedNumber;
}
export interface DropShadowEffect {
  type: "dropShadow";
  color: string;
  blur: AnimatedNumber;
  offsetX?: AnimatedNumber;
  offsetY?: AnimatedNumber;
}
export interface DownscaleBlurEffect {
  type: "downscaleBlur";
  radius: AnimatedNumber;
  shrink: AnimatedNumber;
}
export interface TextLayer {
  type: "text";
  content: string | TemplateString;
  font?: Font;
  color?: string;
  align?: "left" | "center" | "right";
  position?: Point;
  maxWidth?: number;
  shrinkToFit?: boolean;
  minSize?: number;
  wrap?: boolean;
  lineHeight?: number;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface TemplateString {
  template: string;
  bindings?: {
    [k: string]: unknown;
  };
}
export interface Font {
  asset?: string;
  size: number;
  weight?: number;
}
export interface ImageLayer {
  type: "image";
  asset: string;
  frame?: Frame;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface Frame {
  x: number;
  y: number;
  w: number;
  h: number;
  radius?: number;
}
export interface GroupLayer {
  type: "group";
  children: Layer[];
  position?: Point;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface RefLayer {
  type: "ref";
  src: string;
  params?: {
    [k: string]: unknown;
  };
  color?: string;
  size?: number;
  position?: Point;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface RepeaterLayer {
  type: "repeater";
  count: number;
  phaseOffsetMs?: number;
  child: Layer;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface CaptionSequenceLayer {
  type: "captionSequence";
  /**
   * @minItems 1
   */
  captions: [CaptionEntry, ...CaptionEntry[]];
  position?: Point;
  font?: Font;
  color?: string;
  maxWidth?: number;
  shrinkToFit?: boolean;
  entrance?: TransitionConfig;
  exit?: TransitionConfig;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface CaptionEntry {
  t: number;
  text: string;
}
export interface TransitionConfig {
  type: string;
  risePx?: number;
  durationMs?: number;
}
export interface CompositeMaskLayer {
  type: "compositeMask";
  source: string;
  maskEffect?: Effect;
  mask: Layer;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface DataVizLayer {
  type: "dataViz";
  viz: string;
  data: {
    [k: string]: unknown;
  };
  area?: {
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
  };
  style?: {
    [k: string]: unknown;
  };
  animation?: {
    [k: string]: unknown;
  };
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface StatBeatLayer {
  type: "statBeat";
  /**
   * @minItems 1
   */
  beats: [StatBeatEntry, ...StatBeatEntry[]];
  valueFont?: Font;
  valueColor?: string;
  labelFont?: Font;
  labelColor?: string;
  entrance?: string;
  easing?: EasingName;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
}
export interface StatBeatEntry {
  value: number | string;
  label: string;
  position: Point;
  offsetMs?: number;
  countUpMs?: number;
}
