/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Asset = ImageAsset | FontAsset;
export type Background =
  | string
  | {
      type: "linearGradient" | "radialGradient";
      /**
       * @minItems 2
       */
      stops: [string, string, ...string[]];
      angle?: number;
    };
export type Layer =
  | ShapeLayer
  | TextLayer
  | ImageLayer
  | GroupLayer
  | RefLayer
  | RepeaterLayer
  | CaptionSequenceLayer
  | CompositeMaskLayer
  | TrailLayer
  | DataVizLayer
  | StatBeatLayer;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Point = [number, number];
export type AnimatedPoint =
  | Point
  | {
      /**
       * @minItems 1
       */
      keyframes: [PointKeyframe, ...PointKeyframe[]];
    }
  | {
      x: AnimatedNumber;
      y: AnimatedNumber;
    }
  | Generator;
export type EasingName =
  | ("linear" | "easeOutCubic" | "easeInOut" | "easeOutBack" | "easeInCubic")
  | {
      /**
       * @minItems 4
       * @maxItems 4
       */
      bezier: [number, number, number, number];
    };
export type AnimatedNumber =
  | number
  | {
      /**
       * @minItems 1
       */
      keyframes: [NumberKeyframe, ...NumberKeyframe[]];
    }
  | Generator;
export type AnimatedScale =
  | number
  | Point
  | {
      /**
       * @minItems 1
       */
      keyframes: [NumberKeyframe, ...NumberKeyframe[]];
    }
  | {
      /**
       * @minItems 1
       */
      keyframes: [PointKeyframe, ...PointKeyframe[]];
    }
  | Generator;
export type Effect = GaussianBlurEffect | DropShadowEffect | DownscaleBlurEffect;
/**
 * A predicate over `vars` deciding whether a layer is drawn at all — the one place document structure, rather than a value, may depend on a runtime fact. A layer that fails its condition is skipped entirely, and nothing moves to fill the gap: layout stays the author's job, so a document with an optional layer positions the layers around it for both cases. The string form names a var, with or without the `$var:` prefix, and holds when the value is truthy: `false`, `0`, `NaN`, the empty string, the strings `"false"` and `"0"`, and an unset var are all false, everything else true. The object form compares instead, as strings, so `1` and `"1"` match — an unset var never matches.
 */
export type Condition =
  | string
  | {
      /**
       * The name of a var, without the `$var:` prefix.
       */
      var: string;
      /**
       * Holds when the var equals this value. Mutually exclusive with `in`.
       */
      equals?: string | number | boolean;
      /**
       * Holds when the var equals any of these values. Mutually exclusive with `equals`.
       */
      in?: (string | number | boolean)[];
      /**
       * Inverts the whole test, including the truthiness form.
       */
      not?: boolean;
    };

/**
 * A declarative JSON format for motion-graphics videos, inspired by the Lottie schema.
 */
export interface VideoDocument {
  $schema?: string;
  version: 1;
  width: number;
  height: number;
  fps: number;
  durationMs: number;
  vars?: Vars;
  assets?: Assets;
  tokens?: Tokens;
  /**
   * @minItems 1
   */
  scenes: [Scene, ...Scene[]];
  [k: string]: unknown;
}
export interface Vars {
  [k: string]: VarDefinition;
}
export interface VarDefinition {
  type: "string" | "number" | "boolean";
  required?: boolean;
  default?: unknown;
}
export interface Assets {
  [k: string]: Asset;
}
export interface ImageAsset {
  type: "image";
  src: string;
}
/**
 * A typeface the document expects to be available. Declaring it does not load it: the renderer never fetches a face, so the host must have the family loaded before the first frame is drawn. An unloaded family falls through `fallback` to a generic and renders in the wrong typeface with no error, so preload every font asset a document declares — `requiredFonts(doc)` in @variax-ai/video-renderer lists them.
 */
export interface FontAsset {
  type: "font";
  /**
   * The CSS family name the loaded face is registered under. Must match the host's registration exactly, including case.
   */
  family: string;
  /**
   * Additional families tried after `family`, in order, forming the CSS font stack.
   */
  fallback?: string[];
  /**
   * Default weight for text bound to this asset, used when the text layer's font declares none. Defaults to 400.
   */
  weight?: number;
  /**
   * Where the face can be obtained. Advisory only — the renderer never reads it. It is recorded so a host (or a build step) knows what to load for `family`.
   */
  src: string;
}
export interface Tokens {
  [k: string]: string;
}
export interface Scene {
  id: string;
  startMs: number;
  endMs: number;
  background?: Background;
  layers: Layer[];
}
export interface ShapeLayer {
  type: "shape";
  shape: "rect" | "roundedRect" | "ellipse" | "path" | "line";
  /**
   * @minItems 2
   * @maxItems 2
   */
  size?: [number, number];
  radius?: number;
  fill?: string;
  stroke?: Stroke;
  shadow?: Shadow;
  path?: string;
  position?: Point;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface Stroke {
  color: string;
  width: number;
}
export interface Shadow {
  color: string;
  blur: number;
  offsetX?: number;
  offsetY?: number;
}
export interface Transform {
  position?: AnimatedPoint;
  scale?: AnimatedScale;
  rotation?: AnimatedNumber;
  opacity?: AnimatedNumber;
  anchor?: Point;
}
export interface PointKeyframe {
  t: number;
  value: Point;
  easing?: EasingName;
}
export interface NumberKeyframe {
  t: number;
  value: number;
  easing?: EasingName;
}
export interface Generator {
  generator: {
    fn: "sine" | "sineStrokes" | "sineOscillation" | "pulse" | "countUp";
    /**
     * Generator parameters. Every generator additionally accepts `startMs`, which shifts its time origin: the generator is evaluated at `tMs - startMs`. Defaults to 0 (absolute clip time).
     */
    params?: {
      [k: string]: unknown;
    };
    id?: string;
  };
}
export interface GaussianBlurEffect {
  type: "gaussianBlur";
  radius: AnimatedNumber;
}
export interface DropShadowEffect {
  type: "dropShadow";
  color: string;
  blur: AnimatedNumber;
  offsetX?: AnimatedNumber;
  offsetY?: AnimatedNumber;
}
export interface DownscaleBlurEffect {
  type: "downscaleBlur";
  radius: AnimatedNumber;
  shrink: AnimatedNumber;
}
export interface TextLayer {
  type: "text";
  content: string | TemplateString;
  font?: Font;
  color?: string;
  align?: "left" | "center" | "right";
  position?: Point;
  maxWidth?: number;
  shrinkToFit?: boolean;
  minSize?: number;
  wrap?: boolean;
  lineHeight?: number;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface TemplateString {
  template: string;
  bindings?: {
    [k: string]: unknown;
  };
}
export interface Font {
  asset?: string;
  size: number;
  weight?: number;
}
export interface ImageLayer {
  type: "image";
  asset: string;
  frame?: Frame;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface Frame {
  x: number;
  y: number;
  w: number;
  h: number;
  radius?: number;
}
export interface GroupLayer {
  type: "group";
  children: Layer[];
  position?: Point;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface RefLayer {
  type: "ref";
  src: string;
  params?: {
    [k: string]: unknown;
  };
  color?: string;
  size?: number;
  position?: Point;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface RepeaterLayer {
  type: "repeater";
  count: number;
  phaseOffsetMs?: number;
  child: Layer;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface CaptionSequenceLayer {
  type: "captionSequence";
  /**
   * @minItems 1
   */
  captions: [CaptionEntry, ...CaptionEntry[]];
  position?: Point;
  font?: Font;
  color?: string;
  maxWidth?: number;
  shrinkToFit?: boolean;
  entrance?: TransitionConfig;
  exit?: TransitionConfig;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface CaptionEntry {
  t: number;
  text: string;
}
export interface TransitionConfig {
  type: string;
  risePx?: number;
  durationMs?: number;
}
/**
 * Re-draws `source` through a different effect pipeline, clipped to the alpha of `mask`. `maskEffect` applies to the string form of `source` only; when `source` is a Layer, that layer's own `effects` are the pipeline.
 */
export interface CompositeMaskLayer {
  type: "compositeMask";
  /**
   * Either an images-registry key (drawn full-canvas) or a Layer, which is drawn through the normal layer pipeline and so honours `frame` and `downscaleBlur`.
   */
  source: string | Layer;
  maskEffect?: Effect;
  mask: Layer;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
/**
 * Motion history: samples `source` at past times and unions a circle per sample, radius shrinking with age. Emits vector geometry only (no imagery), which is what makes it usable as a compositeMask mask. `source` is the moving point whose path is sampled — it must be declarative so the renderer can re-evaluate it at past times, and is interpreted in absolute document coordinates. `radius` is the radius of the freshest sample. `stroke` draws a polyline through the sample centres with round caps and joins. Samples older than the layer's own `startMs` are dropped.
 */
export interface TrailLayer {
  type: "trail";
  source: AnimatedPoint;
  /**
   * How far back the trail reaches. Sample i sits at `tMs - i * windowMs / samples`.
   */
  windowMs: number;
  /**
   * Number of samples in the age schedule.
   */
  samples: number;
  /**
   * Draw only the N freshest samples, keeping the age schedule computed over `samples`. Defaults to `samples`.
   */
  take?: number;
  radius: AnimatedNumber;
  /**
   * Fraction of the radius shed across the full window: sample i has radius `radius * (1 - falloff * i / samples)`. Defaults to 0.
   */
  falloff?: number;
  /**
   * Fills the union of circles. Defaults to #ffffff when no `stroke` is given.
   */
  fill?: string;
  stroke?: Stroke;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface DataVizLayer {
  type: "dataViz";
  viz: string;
  data: {
    [k: string]: unknown;
  };
  area?: {
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
  };
  style?: {
    [k: string]: unknown;
  };
  animation?: {
    [k: string]: unknown;
  };
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface StatBeatLayer {
  type: "statBeat";
  /**
   * @minItems 1
   */
  beats: [StatBeatEntry, ...StatBeatEntry[]];
  valueFont?: Font;
  valueColor?: string;
  labelFont?: Font;
  labelColor?: string;
  entrance?: string;
  easing?: EasingName;
  transform?: Transform;
  effects?: Effect[];
  startMs?: number;
  endMs?: number;
  persist?: boolean;
  visibleIf?: Condition;
}
export interface StatBeatEntry {
  value: number | string;
  label: string;
  position: Point;
  offsetMs?: number;
  countUpMs?: number;
}
